# Generated by Django 5.1.4 on 2026-07-14 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0003_examsession_course_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('invigilator', 'Invigilator'), ('student', 'Student')], db_index=True, max_length=16)),
                ('method', models.CharField(choices=[('self', 'Self'), ('bulk', 'Bulk (security)')], db_index=True, max_length=16)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('late', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', help_text="Free-text note about where the check-in happened (e.g. 'main door', 'staff entrance').", max_length=120)),
                ('recorded_by', models.ForeignKey(help_text='User who created this row. Equal to ``user`` for self check-in; equal to the security officer for bulk check-in.', on_delete=django.db.models.deletion.PROTECT, related_name='checkins_recorded', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='exams.examsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-at',),
                'indexes': [models.Index(fields=['session', 'kind'], name='attendance__session_f3b77c_idx'), models.Index(fields=['user', '-at'], name='attendance__user_id_81ba82_idx')],
                'unique_together': {('session', 'user', 'kind')},
            },
        ),
    ]
