# Generated by Django 5.1.4 on 2026-07-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='signature_image',
            field=models.TextField(blank=True, default='', help_text='Base64-encoded PNG of the e-signature captured at the door.'),
        ),
    ]
