"""HTTP layer for the AI assistant.

A single POST endpoint. The frontend sends a free-form message and
gets back ``{reply, suggestions, intent, context}``. The reply is
the markdown string; ``suggestions`` are tap-to-fill chips the
frontend renders under the response.

# Phase 19 — OpenRouter
# When ``settings.OPENROUTER_API_KEY`` is set, the reply is generated
# by an LLM call (see ``apps.ai.services.compose_reply_llm``). The
# live DB context is still built by ``build_context()`` and passed to
# the LLM as the source of truth, so the LLM cites real values
# rather than inventing them. When the key is empty (or the LLM call
# fails), the view falls back to the deterministic rule-based path
# (``compose_reply``) so dev machines without an OpenRouter key
# still work.
"""
from __future__ import annotations

import asyncio
import logging

from asgiref.sync import async_to_sync
from django.conf import settings
from drf_spectacular.utils import OpenApiExample, extend_schema
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.throttling import UserRateThrottle
from rest_framework.views import APIView

from .openrouter import OpenRouterError
from .services import build_context, compose_reply, compose_reply_llm, _user_role_code


logger = logging.getLogger("invigilo.ai")


# Per-user rate limit for the chat endpoint. The global UserRateThrottle
# is 1000/min, fine for browsing but way too high for an LLM endpoint
# (a user could burn through 1000 OpenRouter calls in a minute). 30/min
# is more than any human can read in that window.
class ChatUserThrottle(UserRateThrottle):
    scope = "ai_chat"


def _context_to_dict(ctx) -> dict:
    """Serialise the live context the reply was built from. Kept
    small — the assistant answer is the product; the context is a
    debugging aid for the frontend "what did the AI see?" tooltip."""
    return {
        "active_period": ctx.period.code if ctx.period else None,
        "upcoming_session_count": len(ctx.upcoming_sessions),
        "open_conflict_count": len(ctx.open_conflicts),
        "open_incident_count": len(ctx.open_incidents),
        "invigilator_total": ctx.invigilator_total,
        "invigilator_unavailable_today": ctx.invigilator_unavailable_today,
        "latest_run_id": str(ctx.latest_run.id) if ctx.latest_run else None,
        "latest_run_coverage": (
            float(ctx.latest_run.capacity_utilisation) if ctx.latest_run else None
        ),
        "generated_at": ctx.generated_at.isoformat(),
    }


@extend_schema(
    tags=["ai"],
    summary="Ask the AI assistant a question.",
    description=(
        "The assistant is fed live data from the database (active period, "
        "upcoming sessions, open conflicts and incidents, latest engine run). "
        "When OPENROUTER_API_KEY is set, replies are generated by an LLM "
        "grounded in that live context. When the key is empty, the assistant "
        "falls back to a deterministic rule-based path so dev environments "
        "work without an OpenRouter account."
    ),
    request={"application/json": {"type": "object", "properties": {"message": {"type": "string"}}}},
    responses={200: {"type": "object"}},
    examples=[
        OpenApiExample(
            "Status question",
            value={"message": "What's the status of the current cycle?"},
            request_only=True,
        ),
    ],
)
class ChatView(APIView):
    permission_classes = [IsAuthenticated]
    throttle_classes = [ChatUserThrottle]

    def post(self, request):  # type: ignore[no-untyped-def]
        message = (request.data.get("message") or "").strip()
        if not message:
            return Response(
                {"detail": "message is required"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        if len(message) > 500:
            return Response(
                {"detail": "message must be 500 characters or fewer"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        ctx = build_context()
        llm_meta: dict | None = None

        # Try the LLM path when the operator has configured an
        # OpenRouter key. The rule-based path is the deterministic
        # fallback for empty key + LLM errors alike — both cases
        # log differently so the operator can tell them apart.
        if settings.OPENROUTER_API_KEY:
            # ``_user_role_code`` hits the DB for the user's role
            # assignments. It must run before we enter the async
            # bridge — sync ORM access inside async is a hard error.
            try:
                role = _user_role_code(request.user)
            except Exception:  # noqa: BLE001
                logger.exception("ai.chat role lookup failed; falling back")
                role = "GUEST"
            try:
                reply, suggestions, intent, llm_meta = async_to_sync(compose_reply_llm)(
                    request.user, message, ctx, role
                )
                logger.info(
                    "ai.chat user=%s intent=%s model=%s latency_ms=%s prompt=%s completion=%s",
                    getattr(request.user, "email", "anon"),
                    intent,
                    llm_meta.get("model") if llm_meta else "?",
                    llm_meta.get("latency_ms") if llm_meta else "?",
                    llm_meta.get("prompt_tokens") if llm_meta else "?",
                    llm_meta.get("completion_tokens") if llm_meta else "?",
                )
            except OpenRouterError as exc:
                logger.warning(
                    "ai.chat user=%s openrouter_error status=%s detail=%r",
                    getattr(request.user, "email", "anon"),
                    exc.status_code,
                    exc.detail[:120],
                )
                reply, suggestions, intent = compose_reply(message, ctx)
            except Exception:  # noqa: BLE001 — last-resort fallback
                logger.exception("ai.chat user=%s unexpected llm error", request.user)
                reply, suggestions, intent = compose_reply(message, ctx)
        else:
            reply, suggestions, intent = compose_reply(message, ctx)
            logger.info(
                "ai.chat user=%s intent=%s mode=rule_based",
                getattr(request.user, "email", "anon"),
                intent,
            )

        return Response(
            {
                "reply": reply,
                "suggestions": suggestions,
                "intent": intent,
                "context": _context_to_dict(ctx),
            },
            status=status.HTTP_200_OK,
        )
