# Generated by Django 5.1.4 on 2026-07-09 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('invigilators', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('sessions_total', models.PositiveIntegerField(default=0)),
                ('sessions_placed', models.PositiveIntegerField(default=0)),
                ('avg_workload', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_workload', models.PositiveSmallIntegerField(default=0)),
                ('capacity_utilisation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('runtime_seconds', models.PositiveIntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_runs', to='exams.examperiod')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(default='invigilator', help_text="Free-text: 'chief', 'invigilator', 'reserve', etc.", max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='invigilators.invigilatorprofile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='rooms.room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='exams.examsession')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='allocations.allocationrun')),
            ],
            options={
                'ordering': ('session__starts_at', 'invigilator__user__full_name'),
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('double_booking', 'Invigilator double-booked'), ('dept_mix', 'Department-mix violation'), ('no_eligible_invigilators', 'No eligible invigilators'), ('no_room_capacity', 'No room with enough capacity'), ('workload_cap', 'Workload cap exceeded'), ('unavailability', 'Invigilator unavailable')], max_length=64)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], default='error', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='invigilators.invigilatorprofile')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='allocations.allocationrun')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='exams.examsession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='allocationrun',
            index=models.Index(fields=['period', '-created_at'], name='allocations_period__c0932b_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['session', 'status'], name='allocations_session_b9172b_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['invigilator', 'status'], name='allocations_invigil_c34eaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('session', 'invigilator'), name='allocations_unique_session_invigilator'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['run', 'type'], name='allocations_run_id_3f9546_idx'),
        ),
    ]
