# Generated by Django 5.1.4 on 2026-07-09 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='audit_audit_target__edb7ad_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx')],
            },
        ),
    ]
