# Generated by Django 5.1.4 on 2026-07-09 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ('-starts_on', 'code'),
                'indexes': [models.Index(fields=['is_active', 'starts_on'], name='exams_examp_is_acti_1f0ed7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('registered', models.PositiveIntegerField(default=0)),
                ('invigilators_required', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ready', 'Ready'), ('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=24)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='academic.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='exams.examperiod')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='rooms.room')),
            ],
            options={
                'ordering': ('starts_at', 'course__code'),
                'indexes': [models.Index(fields=['period', 'status'], name='exams_exams_period__308e87_idx'), models.Index(fields=['starts_at', 'ends_at'], name='exams_exams_starts__e398e8_idx')],
            },
        ),
    ]
