# Generated by Django 5.1.4 on 2026-07-10 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_seed_university_campus_units'),
        ('exams', '0002_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='course_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='academic.courseunit'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='special_requirements',
            field=models.TextField(blank=True, default='', help_text='Free-text notes about special arrangements (e.g. large-print papers, extra time, separate venue, specific equipment).'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('ready', 'Ready'), ('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=24),
        ),
    ]
