# Generated by Django 5.1.4 on 2026-07-15 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_studentregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QrToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hex of the raw token; the raw token is never stored.', max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=16)),
                ('scope', models.CharField(choices=[('session', 'Session-bound (student)'), ('self', 'Self (invigilator / EO / admin)')], max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='exams.studentregistration')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='exams.examsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['expires_at', 'revoked_at'], name='exams_qrtok_expires_62eddd_idx'), models.Index(fields=['kind', 'scope'], name='exams_qrtok_kind_b9ebac_idx')],
            },
        ),
    ]
