# Generated by Django 5.1.4 on 2026-07-09 09:01

import apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_rbac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'base_manager_name': 'all_objects', 'ordering': ('email',)},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.managers.SoftDeleteUserManager()),
                ('all_objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='accounts_rolepermission_unique',
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='accounts_userrole_unique',
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='accounts_ro_role_id_5b564a_idx',
            old_name='accounts_rp_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_is_acti_cfc41a_idx',
            old_name='accounts_user_active_verified_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='accounts_us_user_id_5c3bd8_idx',
            old_name='accounts_userrole_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
