# Generated by Django 5.1.4 on 2026-07-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_user_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
