# Generated by Django 5.1.4 on 2026-07-09 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('max_sessions_per_cycle', models.PositiveSmallIntegerField(default=6)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('primary_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilators', to='academic.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__full_name',),
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('off_duty', 'Off duty'), ('leave', 'On leave')], default='available', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='invigilators.invigilatorprofile')),
            ],
            options={
                'ordering': ('date',),
                'indexes': [models.Index(fields=['date', 'status'], name='invigilator_date_f31ddb_idx')],
                'unique_together': {('invigilator', 'date')},
            },
        ),
    ]
