# Generated by Django 5.1.4 on 2026-07-09 09:01

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=8)),
                ('audience', models.CharField(choices=[('internal', 'Internal'), ('registrar', 'Registrar'), ('senate', 'Senate'), ('public', 'Public')], default='internal', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.reports.models._report_upload_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports', to='exams.examperiod')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-generated_at',),
                'indexes': [models.Index(fields=['format', '-generated_at'], name='reports_rep_format_ec8006_idx')],
            },
        ),
    ]
